// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAy0lPm1ylj2MQNF_ahWv_QldAm4WrgU',
    appId: '1:905292851305:web:ac445dfc235da81e859af8',
    messagingSenderId: '905292851305',
    projectId: 'insidex-app-3fe91',
    authDomain: 'insidex-app-3fe91.firebaseapp.com',
    storageBucket: 'insidex-app-3fe91.firebasestorage.app',
    measurementId: 'G-JVXM7KDL3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubQE23lq5GEZK9TM_Fv36vB3zMUz1VYg',
    appId: '1:905292851305:android:330bfe84c8a511d5859af8',
    messagingSenderId: '905292851305',
    projectId: 'insidex-app-3fe91',
    storageBucket: 'insidex-app-3fe91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUWw22lXHgfJp_RuFtaDEHC5U5-FuJjzU',
    appId: '1:905292851305:ios:29180f57c02989c0859af8',
    messagingSenderId: '905292851305',
    projectId: 'insidex-app-3fe91',
    storageBucket: 'insidex-app-3fe91.firebasestorage.app',
    iosBundleId: 'com.example.insidexApp',
  );
}
